### PR TITLE
UIFR-90

### PR DESCRIPTION
**Pull request by maywuy**

### CODE REVIEW

**Comment by maywuy** [comment]
merge request for UIFR-90

**Comment by dkayiwa** [comment]
@maywuy can you add a unit test?

**Comment by maywuy** [comment]
@dkayiwa  sure!

**Comment by dkayiwa** [comment]
@maywuy are you still working on this?

**Comment by maywuy** [comment]
Yes.


On May 2, 2017, at 4:29 AM, dkayiwa <notifications@github.com<mailto:notifications@github.com>> wrote:


@maywuy<https://github.com/maywuy> are you still working on this?

**Pull request merged**
