### PR TITLE
RA-1212 Introduce convenient way to override existing page

### PR DESCRIPTION
**Pull request by PawelGutkowski**
https://issues.openmrs.org/browse/RA-1212

work still in progress

### CODE REVIEW

**Comment by dkayiwa** [comment]
@PawelGutkowski how is this going? :)

**Comment by PawelGutkowski** [comment]
It kind of got stuck with UI, because I wanted to solve problem with cross distro UI first, I've made working prototype, but works on this didn't advance lately.

**Comment by dkayiwa** [comment]
@PawelGutkowski did you notice the merge conflicts on this?

**Comment by dkayiwa** [comment]
@PawelGutkowski did you notice the merge conflicts on this?

**Comment by dkayiwa** [comment]
@PawelGutkowski did you see the above?

**Comment by dkayiwa** [comment]
@PawelGutkowski ping me to reopen this when you get some time to resume. :)

**Pull request closed without merging**
