### PR TITLE
UIFR-158: create german messages.propertie

### PR DESCRIPTION
**Pull request by STheis**
german translation of UI Framework

### CODE REVIEW

**Comment by djazayeri** [comment]
Same as the comment I just left of the idgen PR: can you also modify the config.xml file in this pull request?

**Comment by STheis** [comment]
Is this ok so?

**Comment by djazayeri** [comment]
The final outcome of this PR is correct. If possible, I'd prefer to avoid merging this as 3 commits (particularly the merge one isn't nice).

Can you squash the commits into one?

**Comment by STheis** [comment]
opened new PR #26. can't squash the commits

**Pull request closed without merging**
